scylla_nic: "{{ ansible_default_ipv4.interface }}"
scylla_nic_ipv4_addr: "{{ vars['ansible_'~scylla_nic].ipv4.address }}"

delete_cassandra_user: true

scylla_admin_username: scylla_admin

# Every user defined here must be also defined in the inventory file
# under the section [cql_credentials] followed by its password.
internal_users:
  scylla_cql_monitor:
    superuser: false
    permissions:
      - ['SELECT', 'KEYSPACE SYSTEM']
  scylla_cql_manager:
    superuser: false
    permissions:
    - ['DESCRIBE', 'ALL ROLES']
    - ['SELECT', 'KEYSPACE system']
    - ['SELECT', 'KEYSPACE system_schema']

# Differently from internal users, the password for customer users
# must be defined only here, and not in the inventory.
# customer_users:
#   customer_admin:
#     password: p@ssw0rd1
#     permissions:
#       - ['CREATE', 'ALL ROLES']
#       - ['AUTHORIZE', 'ALL ROLES']
#       - ['DESCRIBE', 'ALL ROLES']
#       - ['AUTHORIZE', 'ALL KEYSPACES']
#       - ['CREATE', 'ALL KEYSPACES']
#       - ['ALTER', 'ALL KEYSPACES']
#       - ['SELECT', 'ALL KEYSPACES']
#       - ['MODIFY', 'ALL KEYSPACES']
#       - ['AUTHORIZE', 'ALL KEYSPACES']
#       - ['ALTER', 'ALL ROLES'] # This is a workaround and should be removed once {https://github.com/scylladb/scylladb/issues/14279} is fixed
#   another_customer_user:
#     password: p@ssw0rd2
#     permissions:
#       - ['SELECT', 'ALL KEYSPACES']
